index:
    path: /
    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]

register:
    path: /register
    controller: App\Controller\UserController::register
    methods: [POST]

delete:
    path: /delete/{id}
    controller: App\Controller\UserController::delete
    methods: [DELETE]

user_id:
    path: /users/{id}
    controller: App\Controller\UserController::getUserById
    methods: [GET]

user_recipes:
    path: /users/{id}/recipes
    controller: App\Controller\RecipesController::getAllUserLikedRecipes
    methods: [GET]

