<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6U2loJJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6U2loJJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6U2loJJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6U2loJJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6U2loJJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6U2loJJ',
    'container.build_id' => '1b7590e9',
    'container.build_time' => 1775935311,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6U2loJJ');
