<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB0tUphg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB0tUphg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB0tUphg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB0tUphg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerB0tUphg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'B0tUphg',
    'container.build_id' => 'b308d560',
    'container.build_time' => 1776974999,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB0tUphg');
