<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2W3Zeqx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2W3Zeqx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2W3Zeqx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2W3Zeqx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2W3Zeqx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2W3Zeqx',
    'container.build_id' => '7ecdfde5',
    'container.build_time' => 1776974074,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2W3Zeqx');
